"""Generate sql/lab/04_kpi_history.sql: 4 weeks of shipped outbound orders per facility.

Synthetic history for the Client KPI Scorecard: ~15 shipped orders a week per facility,
1-3 lines each, with a small number of late shipments (clustered in one week so the
trend shows a dip) and a few short-shipped lines (fill rate just under 100%).
Deterministic (fixed seed), so rerunning produces the same SQL.

    python bip-report/tools/build_kpi_history_sql.py
"""
import random
from datetime import date, timedelta
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "sql" / "lab" / "04_kpi_history.sql"

PERIOD_END = date(2026, 9, 25)          # last shipping day in the history
DAYS = 28                               # 4 weeks
FACILITIES = [("PERRIS", "PER", [142, 155, 163, 171, 188, 204]),
              ("ATLANTA", "ATL", [317, 322, 336, 348, 351, 369])]
SKUS = [f"TIRE-00{i}" for i in range(1, 9)]
ORDERS_PER_FACILITY = 60

rng = random.Random(20260925)


def sql_date(d):
    return f"DATE('{d.isoformat()}')"


orders, lines = [], []
for code, abbrev, stores in FACILITIES:
    for k in range(1, ORDERS_PER_FACILITY + 1):
        promised = PERIOD_END - timedelta(days=rng.randrange(DAYS))
        if promised.weekday() == 6:                      # no Sunday shipping
            promised -= timedelta(days=1)
        weeks_back = (PERIOD_END - promised).days // 7   # 0 = most recent week
        # Late: rare overall, more common two weeks back (a bad week the trend shows).
        late_chance = 0.16 if weeks_back == 2 else 0.03
        late_days = rng.choice([1, 1, 2]) if rng.random() < late_chance else 0
        actual = min(promised + timedelta(days=late_days), PERIOD_END)
        if actual == promised:
            late_days = 0
        order_no = f"HS-{abbrev}-{k:04d}"
        store = rng.choice(stores)
        orders.append((order_no, code, f"Hello World Tire - Store #{store:04d}",
                       promised - timedelta(days=3), promised, actual, f"PO-{abbrev}{k:05d}"))
        for line_no, sku in enumerate(rng.sample(SKUS, rng.choice([1, 2, 2, 3])), 1):
            qty = rng.choice([8, 12, 16, 20, 24, 32, 40, 48])
            shipped = qty
            if rng.random() < 0.04:                      # short-shipped line
                shipped = qty - rng.choice([2, 4, 8])
            lines.append((order_no, line_no, sku, qty, shipped, shipped))

order_rows = ",\n".join(
    f"    ('{o}', '{w}', '{c}', {sql_date(od)}, {sql_date(p)}, {sql_date(a)}, '{po}')"
    for o, w, c, od, p, a, po in orders)
line_rows = ",\n".join(
    f"    ('{o}', {n}, '{s}', {q}, {pk}, {sh})" for o, n, s, q, pk, sh in lines)

late = sum(1 for o in orders if o[5] > o[4])
units = sum(l[3] for l in lines)
short = sum(l[3] - l[5] for l in lines)

sql = f"""-- ============================================================================
-- KPI history: 4 weeks of shipped outbound orders per facility (synthetic).
-- GENERATED by tools/build_kpi_history_sql.py - edit the generator, not this file.
--
-- {len(orders)} orders ({ORDERS_PER_FACILITY} per facility), {len(lines)} lines, {units} units ordered.
-- {late} orders shipped late (clustered two weeks before {PERIOD_END}),
-- {short} units short-shipped. Customer POs are fictional.
--
-- Simplification: these historical shipments do not post SHIP transactions or
-- reduce inventory, so the aging, heatmap and BOL data stay as they are.
--
-- Backups first (BAK20260925.*_B3). Run once, all-or-nothing:
--   db2 +c -s -tf 04_kpi_history.sql
-- ============================================================================

CONNECT TO TIREWMS;

CREATE TABLE BAK20260925.OUTBOUND_ORDER_B3 AS (SELECT * FROM WMS.OUTBOUND_ORDER) WITH DATA;
CREATE TABLE BAK20260925.OUTBOUND_LINE_B3 AS (SELECT * FROM WMS.OUTBOUND_LINE) WITH DATA;

-- Orders: SHIPPED, with promised and actual ship dates
INSERT INTO WMS.OUTBOUND_ORDER
    (ORDER_ID, ORDER_NUMBER, WAREHOUSE_ID, CUSTOMER_NAME, ORDER_DATE, PROMISED_SHIP_DATE,
     ACTUAL_SHIP_DATE, ORDER_STATUS, CARRIER_CODE, SHIPMENT_ID, CUSTOMER_PO)
WITH O (ORDER_NUMBER, WH, CUST, ORDER_DATE, PROMISED, ACTUAL, PO) AS (VALUES
{order_rows}),
BASE AS (SELECT MAX(ORDER_ID) AS MAXID FROM WMS.OUTBOUND_ORDER)
SELECT BASE.MAXID + ROW_NUMBER() OVER (ORDER BY O.ORDER_NUMBER), O.ORDER_NUMBER, w.WAREHOUSE_ID,
       O.CUST, O.ORDER_DATE, O.PROMISED, O.ACTUAL, 'SHIPPED', 'DEMO-LTL', CAST(NULL AS INTEGER), O.PO
FROM O JOIN WMS.WAREHOUSE w ON w.WAREHOUSE_CODE = O.WH, BASE;

-- Lines: ordered, picked and shipped quantities (short-shipped lines pick and ship less)
INSERT INTO WMS.OUTBOUND_LINE (ORDER_ID, LINE_NUMBER, ITEM_ID, ORDERED_QTY, PICKED_QTY, SHIPPED_QTY)
WITH L (ORDER_NUMBER, LINE_NUMBER, SKU, ORDERED, PICKED, SHIPPED) AS (VALUES
{line_rows})
SELECT o.ORDER_ID, L.LINE_NUMBER, i.ITEM_ID, L.ORDERED, L.PICKED, L.SHIPPED
FROM L JOIN WMS.OUTBOUND_ORDER o ON o.ORDER_NUMBER = L.ORDER_NUMBER
       JOIN WMS.ITEM i ON i.SKU = L.SKU;

-- The scorecard reads receipts and putaways; the report user needs SELECT on transactions
GRANT SELECT ON WMS.INVENTORY_TRANSACTION TO USER RPTVIEW;

COMMIT;

-- Checks: per facility, orders / late / units ordered / units shipped
SELECT w.WAREHOUSE_CODE, COUNT(DISTINCT o.ORDER_ID) AS ORDERS,
       COUNT(DISTINCT CASE WHEN o.ACTUAL_SHIP_DATE > o.PROMISED_SHIP_DATE THEN o.ORDER_ID END) AS LATE,
       SUM(l.ORDERED_QTY) AS UNITS_ORDERED, SUM(l.SHIPPED_QTY) AS UNITS_SHIPPED
FROM WMS.OUTBOUND_ORDER o
JOIN WMS.OUTBOUND_LINE l ON l.ORDER_ID = o.ORDER_ID
JOIN WMS.WAREHOUSE w ON w.WAREHOUSE_ID = o.WAREHOUSE_ID
WHERE o.ORDER_NUMBER LIKE 'HS-%'
GROUP BY w.WAREHOUSE_CODE;

CONNECT RESET;
"""
OUT.write_text(sql, encoding="utf-8")
print(f"wrote {OUT}: {len(orders)} orders, {len(lines)} lines, {late} late, {short} units short")
