import React, { useEffect, useState } from "react";
import { authFetch } from "./apiClient.js";

const API_BASE = import.meta.env.VITE_API_BASE || "http://localhost:8000";

const PENDING_STATUS = "Pending Gate 1 review";

function statusBadgeClass(status) {
  if (status === PENDING_STATUS) return "neutral";
  if (status.startsWith("Approved")) return "good";
  if (status.startsWith("Rejected") || status.startsWith("Auto-denied")) return "bad";
  return "neutral";
}

function tierBadgeClass(tier) {
  if (tier === "A") return "good";
  if (tier === "B") return "ready";
  return "bad";
}

export default function AdminChangeRequests() {
  const [requests, setRequests] = useState([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [actioningCr, setActioningCr] = useState(null);

  async function loadRequests() {
    setLoading(true);
    setError(null);
    try {
      const res = await authFetch(`${API_BASE}/api/change-requests`);
      const data = await res.json().catch(() => []);
      if (!res.ok) throw new Error(data.detail || "Failed to load change requests.");
      setRequests(Array.isArray(data) ? data : []);
    } catch (err) {
      setError(err.message || "Failed to load change requests.");
    } finally {
      setLoading(false);
    }
  }

  async function decide(crNumber, decision) {
    setActioningCr(crNumber);
    setError(null);
    try {
      const res = await authFetch(`${API_BASE}/api/change-requests/${crNumber}/${decision}`, {
        method: "POST",
      });
      const data = await res.json().catch(() => ({}));
      if (!res.ok) throw new Error(data.detail || `Failed to ${decision} CR-${crNumber}.`);
      setRequests((prev) => prev.map((cr) => (cr.crNumber === crNumber ? data : cr)));
    } catch (err) {
      setError(err.message || `Failed to ${decision} CR-${crNumber}.`);
    } finally {
      setActioningCr(null);
    }
  }

  useEffect(() => {
    loadRequests();
  }, []);

  return (
    <>
      <section className="panel">
        <h2>Change Request Review (Gate 1)</h2>
        <p className="admin-lede">
          Requests generated by the intake pipeline (<code>pipeline/generate_change_request.py</code>),
          waiting on human approval before implementation starts. Tier C requests are auto-denied by the
          pipeline itself and never reach this queue for approval -- they're listed here for visibility only.
        </p>
        {error && <section className="alert"><div><strong>Error</strong><p>{error}</p></div></section>}
        <button onClick={loadRequests} disabled={loading}>
          {loading ? "Loading..." : "Refresh"}
        </button>
      </section>

      <section className="panel">
        <table>
          <thead>
            <tr>
              <th>CR</th>
              <th>Title</th>
              <th>Tier</th>
              <th>Est. tokens</th>
              <th>Est. cost</th>
              <th>Cost ratio</th>
              <th>Status</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            {requests.length === 0 ? (
              <tr><td colSpan="8">No change requests found yet.</td></tr>
            ) : (
              requests.map((cr) => (
                <tr key={cr.crNumber}>
                  <td>CR-{String(cr.crNumber).padStart(3, "0")}</td>
                  <td className="file-name-cell" title={cr.originalRequest}>{cr.title}</td>
                  <td>
                    <span className={`status-badge ${tierBadgeClass(cr.tier)}`}>{cr.tier}</span>
                  </td>
                  <td>{cr.estimatedTokens ?? "—"}</td>
                  <td>{cr.estimatedCost ? `$${cr.estimatedCost}` : "—"}</td>
                  <td>{cr.costRatioPct ? `${cr.costRatioPct}%` : "—"}</td>
                  <td>
                    <span className={`status-badge ${statusBadgeClass(cr.status)}`}>{cr.status}</span>
                  </td>
                  <td>
                    {cr.status === PENDING_STATUS && (
                      <>
                        <button
                          onClick={() => decide(cr.crNumber, "approve")}
                          disabled={actioningCr === cr.crNumber}
                        >
                          Approve
                        </button>{" "}
                        <button
                          onClick={() => decide(cr.crNumber, "reject")}
                          disabled={actioningCr === cr.crNumber}
                        >
                          Reject
                        </button>
                      </>
                    )}
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </section>
    </>
  );
}
