-- ============================================================================
-- Outbound shipment data for the VICS Bill of Lading report (Db2 LUW lab, synthetic).
--
--  * Ship-from addresses on WMS.WAREHOUSE; unit weight and tires-per-pallet on WMS.ITEM.
--  * New WMS.CARRIER, WMS.SHIP_TO and WMS.SHIPMENT (one row per trailer / BOL).
--  * OUTBOUND_ORDER gets SHIPMENT_ID and CUSTOMER_PO.
--  * One loaded trailer per facility: three customer POs for one Hello World Tire
--    store, ~21 pallets. The trailer (SHIPMENT) is LOADED; its orders stay PICKING
--    (fully picked, not yet shipped), since the lab schema limits ORDER_STATUS to
--    RELEASED / PICKING / HOLD / SHIPPED. The BOL is printed at this point, before the
--    driver signs and the orders move to SHIPPED.
--
-- BOL numbers use the VICS 17-digit format: GS1 company prefix + serial + GS1 mod-10
-- check digit. 0614141 is GS1s documentation example prefix, not a real companys.
-- All names, addresses, SCAC, trailer, seal and PRO numbers are fictional.
--
-- Backups first (BAK20260925.*_B2). Run once, all-or-nothing:
--   db2 +c -s -tf 02_outbound_bol.sql
-- ============================================================================

CONNECT TO TIREWMS;

CREATE TABLE BAK20260925.WAREHOUSE_B2 AS (SELECT * FROM WMS.WAREHOUSE) WITH DATA;
CREATE TABLE BAK20260925.ITEM_B2 AS (SELECT * FROM WMS.ITEM) WITH DATA;
CREATE TABLE BAK20260925.OUTBOUND_ORDER_B2 AS (SELECT * FROM WMS.OUTBOUND_ORDER) WITH DATA;
CREATE TABLE BAK20260925.OUTBOUND_LINE_B2 AS (SELECT * FROM WMS.OUTBOUND_LINE) WITH DATA;

-- ---------------------------------------------------------------- reference data
ALTER TABLE WMS.WAREHOUSE
    ADD COLUMN ADDRESS_LINE1 VARCHAR(60)
    ADD COLUMN CITY          VARCHAR(40)
    ADD COLUMN STATE_CODE    CHAR(2)
    ADD COLUMN POSTAL_CODE   VARCHAR(10)
    -- SID# on the BOL
    ADD COLUMN SHIPPER_ID    VARCHAR(20);

UPDATE WMS.WAREHOUSE SET ADDRESS_LINE1 = '1 Demo Distribution Pkwy', CITY = 'Perris',
       STATE_CODE = 'CA', POSTAL_CODE = '92571', SHIPPER_ID = 'HWT-DC-PERRIS'
WHERE WAREHOUSE_CODE = 'PERRIS';
UPDATE WMS.WAREHOUSE SET ADDRESS_LINE1 = '2 Demo Logistics Dr', CITY = 'Atlanta',
       STATE_CODE = 'GA', POSTAL_CODE = '30336', SHIPPER_ID = 'HWT-DC-ATLANTA'
WHERE WAREHOUSE_CODE = 'ATLANTA';

ALTER TABLE WMS.ITEM
    ADD COLUMN UNIT_WEIGHT_LBS  DECIMAL(6,2)
    ADD COLUMN UNITS_PER_PALLET SMALLINT;

UPDATE WMS.ITEM SET UNIT_WEIGHT_LBS = CASE SKU
        WHEN 'TIRE-001' THEN 22 WHEN 'TIRE-002' THEN 23 WHEN 'TIRE-003' THEN 27 WHEN 'TIRE-004' THEN 29
        WHEN 'TIRE-005' THEN 30 WHEN 'TIRE-006' THEN 40 WHEN 'TIRE-007' THEN 45 WHEN 'TIRE-008' THEN 24 END,
    UNITS_PER_PALLET = CASE WHEN DESCRIPTION LIKE '%All Terrain%' THEN 24 ELSE 40 END;

CREATE TABLE WMS.CARRIER (
    CARRIER_CODE VARCHAR(12) NOT NULL PRIMARY KEY,
    CARRIER_NAME VARCHAR(60) NOT NULL,
    SCAC         VARCHAR(4)  NOT NULL
);
INSERT INTO WMS.CARRIER VALUES
    ('DEMO-TL',  'Hello World Freight Lines (demo)', 'HWFL'),
    ('DEMO-LTL', 'Sample LTL Express (demo)',        'SLTX');

CREATE TABLE WMS.SHIP_TO (
    SHIP_TO_ID      INTEGER     NOT NULL PRIMARY KEY,
    SHIP_TO_NAME    VARCHAR(60) NOT NULL,
    ADDRESS_LINE1   VARCHAR(60) NOT NULL,
    CITY            VARCHAR(40) NOT NULL,
    STATE_CODE      CHAR(2)     NOT NULL,
    POSTAL_CODE     VARCHAR(10) NOT NULL,
    LOCATION_NUMBER VARCHAR(10) NOT NULL,   -- Location # on the BOL
    CUSTOMER_ID     VARCHAR(20) NOT NULL    -- CID# on the BOL
);
INSERT INTO WMS.SHIP_TO VALUES
    (1, 'Hello World Tire - Store #0142', '100 Sample Way',      'Riverside', 'CA', '92501', '0142', 'HWT-RETAIL'),
    (2, 'Hello World Tire - Store #0317', '200 Example Blvd',    'Marietta',  'GA', '30060', '0317', 'HWT-RETAIL');

-- One row per trailer / BOL.
CREATE TABLE WMS.SHIPMENT (
    SHIPMENT_ID          INTEGER     NOT NULL PRIMARY KEY,
    BOL_NUMBER           CHAR(17)    NOT NULL UNIQUE,
    WAREHOUSE_ID         INTEGER     NOT NULL REFERENCES WMS.WAREHOUSE,
    SHIP_TO_ID           INTEGER     NOT NULL REFERENCES WMS.SHIP_TO,
    CARRIER_CODE         VARCHAR(12) NOT NULL REFERENCES WMS.CARRIER,
    TRAILER_NUMBER       VARCHAR(15) NOT NULL,
    SEAL_NUMBER          VARCHAR(20) NOT NULL,
    PRO_NUMBER           VARCHAR(15) NOT NULL,
    FREIGHT_TERMS        VARCHAR(12) NOT NULL,   -- PREPAID / COLLECT / THIRD_PARTY
    SHIP_DATE            DATE        NOT NULL,
    SHIPMENT_STATUS      VARCHAR(12) NOT NULL,   -- LOADED / SHIPPED
    TRAILER_LOADED_BY    VARCHAR(8)  NOT NULL,   -- SHIPPER / DRIVER
    FREIGHT_COUNTED_BY   VARCHAR(16) NOT NULL,   -- SHIPPER / DRIVER_PALLETS / DRIVER_PIECES
    SPECIAL_INSTRUCTIONS VARCHAR(200)
);
INSERT INTO WMS.SHIPMENT
SELECT 1, '06141410000000012', w.WAREHOUSE_ID, 1, 'DEMO-TL', 'TRL-53-4471', 'SL-0042718', '8810004201',
       'PREPAID', DATE('2026-09-25'), 'LOADED', 'SHIPPER', 'SHIPPER',
       'Deliver to rear dock, door 2. Appointment 0700-1100. Call store 30 min before arrival.'
FROM WMS.WAREHOUSE w WHERE w.WAREHOUSE_CODE = 'PERRIS';
INSERT INTO WMS.SHIPMENT
SELECT 2, '06141410000000029', w.WAREHOUSE_ID, 2, 'DEMO-TL', 'TRL-53-5190', 'SL-0042955', '8810004218',
       'PREPAID', DATE('2026-09-25'), 'LOADED', 'SHIPPER', 'SHIPPER',
       'Deliver to rear dock. Appointment 0600-1000. Do not double stack pallets.'
FROM WMS.WAREHOUSE w WHERE w.WAREHOUSE_CODE = 'ATLANTA';

-- ---------------------------------------------------------------- the orders on each trailer
ALTER TABLE WMS.OUTBOUND_ORDER
    ADD COLUMN SHIPMENT_ID INTEGER
    ADD COLUMN CUSTOMER_PO VARCHAR(20);

INSERT INTO WMS.OUTBOUND_ORDER
    (ORDER_ID, ORDER_NUMBER, WAREHOUSE_ID, CUSTOMER_NAME, ORDER_DATE, PROMISED_SHIP_DATE,
     ACTUAL_SHIP_DATE, ORDER_STATUS, CARRIER_CODE, SHIPMENT_ID, CUSTOMER_PO)
WITH O (OFFSET, ORDER_NUMBER, WH, CUST, PO, SHIPMENT) AS (VALUES
    (1, 'DEMO-SO-1001', 'PERRIS',  'Hello World Tire - Store #0142', 'PO-4500123', 1),
    (2, 'DEMO-SO-1002', 'PERRIS',  'Hello World Tire - Store #0142', 'PO-4500124', 1),
    (3, 'DEMO-SO-1003', 'PERRIS',  'Hello World Tire - Store #0142', 'PO-4500131', 1),
    (4, 'DEMO-SO-2001', 'ATLANTA', 'Hello World Tire - Store #0317', 'PO-7700415', 2),
    (5, 'DEMO-SO-2002', 'ATLANTA', 'Hello World Tire - Store #0317', 'PO-7700416', 2),
    (6, 'DEMO-SO-2003', 'ATLANTA', 'Hello World Tire - Store #0317', 'PO-7700422', 2)),
BASE AS (SELECT MAX(ORDER_ID) AS MAXID FROM WMS.OUTBOUND_ORDER)
SELECT BASE.MAXID + O.OFFSET, O.ORDER_NUMBER, w.WAREHOUSE_ID, O.CUST,
       DATE('2026-09-22'), DATE('2026-09-25'), CAST(NULL AS DATE), 'PICKING', 'DEMO-TL', O.SHIPMENT, O.PO
FROM O JOIN WMS.WAREHOUSE w ON w.WAREHOUSE_CODE = O.WH, BASE;

-- Lines in full-pallet quantities (40 touring or 24 all-terrain tires per pallet).
INSERT INTO WMS.OUTBOUND_LINE (ORDER_ID, LINE_NUMBER, ITEM_ID, ORDERED_QTY, PICKED_QTY, SHIPPED_QTY)
WITH L (ORDER_NUMBER, LINE_NUMBER, SKU, QTY) AS (VALUES
    ('DEMO-SO-1001', 1, 'TIRE-001', 160), ('DEMO-SO-1001', 2, 'TIRE-002', 120),
    ('DEMO-SO-1002', 1, 'TIRE-003', 120), ('DEMO-SO-1002', 2, 'TIRE-005', 72),
    ('DEMO-SO-1003', 1, 'TIRE-006', 96),  ('DEMO-SO-1003', 2, 'TIRE-008', 96),
    ('DEMO-SO-2001', 1, 'TIRE-002', 200), ('DEMO-SO-2001', 2, 'TIRE-004', 80),
    ('DEMO-SO-2002', 1, 'TIRE-007', 72),  ('DEMO-SO-2002', 2, 'TIRE-006', 48),
    ('DEMO-SO-2003', 1, 'TIRE-003', 160), ('DEMO-SO-2003', 2, 'TIRE-005', 48))
SELECT o.ORDER_ID, L.LINE_NUMBER, i.ITEM_ID, L.QTY, L.QTY, 0
FROM L JOIN WMS.OUTBOUND_ORDER o ON o.ORDER_NUMBER = L.ORDER_NUMBER
       JOIN WMS.ITEM i ON i.SKU = L.SKU;

GRANT SELECT ON WMS.CARRIER TO USER RPTVIEW;
GRANT SELECT ON WMS.SHIP_TO TO USER RPTVIEW;
GRANT SELECT ON WMS.SHIPMENT TO USER RPTVIEW;
GRANT SELECT ON WMS.OUTBOUND_ORDER TO USER RPTVIEW;
GRANT SELECT ON WMS.OUTBOUND_LINE TO USER RPTVIEW;

COMMIT;

-- Checks: per trailer, orders / pallets / tires / weight (tires + 40 lb per pallet).
SELECT s.BOL_NUMBER, w.WAREHOUSE_CODE, COUNT(DISTINCT o.ORDER_ID) AS ORDERS,
       SUM(CEILING(DECIMAL(l.ORDERED_QTY) / i.UNITS_PER_PALLET)) AS PALLETS,
       SUM(l.ORDERED_QTY) AS TIRES,
       SUM(l.ORDERED_QTY * i.UNIT_WEIGHT_LBS + CEILING(DECIMAL(l.ORDERED_QTY) / i.UNITS_PER_PALLET) * 40) AS WEIGHT_LBS
FROM WMS.SHIPMENT s
JOIN WMS.WAREHOUSE w ON w.WAREHOUSE_ID = s.WAREHOUSE_ID
JOIN WMS.OUTBOUND_ORDER o ON o.SHIPMENT_ID = s.SHIPMENT_ID
JOIN WMS.OUTBOUND_LINE l ON l.ORDER_ID = o.ORDER_ID
JOIN WMS.ITEM i ON i.ITEM_ID = l.ITEM_ID
GROUP BY s.BOL_NUMBER, w.WAREHOUSE_CODE;

CONNECT RESET;
